# Generated by Django 5.0.4 on 2024-04-18 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("teams", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="team",
            name="title",
        ),
        migrations.AddField(
            model_name="team",
            name="titles",
            field=models.IntegerField(default="0", null=True),
        ),
        migrations.AlterField(
            model_name="team",
            name="first_cup",
            field=models.DateField(null=True),
        ),
    ]
