# Generated by Django 5.0.4 on 2024-04-18 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("teams", "0002_remove_team_title_team_titles_alter_team_first_cup"),
    ]

    operations = [
        migrations.AlterField(
            model_name="team",
            name="titles",
            field=models.IntegerField(default=0, null=True),
        ),
    ]
